name: y_player_alpha
description: "YPlayer is a Flutter package that provides an easy-to-use YouTube
  video player widget"
version: 2.0.6
repository: https://github.com/bishalregmi105B/y_player

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  media_kit: ^1.2.0
  media_kit_libs_video: ^1.0.6
  media_kit_video: ^1.3.0
  youtube_explode_dart_alpha: ^2.5.3

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
